### ISSUE TITLE
Hack Day V2 (10th June TBC)

### ISSUE THREAD

**Issue by benfoxall** [adventure-collective/lanterns#5]
### Before announcing
- [ ] confirm timings/venue/costs
- [ ] get copy below up to scratch

### Before the event
- [x] complete #1 to make set up easier
- [ ] prepare intro slides [start](https://docs.google.com/presentation/d/1UIOrrFS97ZNtDVChsRHnV-vnie_6UK96R86WIh0Z_vM/edit?usp=sharing)
- [ ] implement layout chooser ui (+maybe live reload)

---

We're working on a project where we control the colours of hundreds of LED fairy lights from a single web page. If that sounds up your street (and trust us, it's awesome fun) - then come along and help out.

There's a few ways that you can get involved:

1. Building demos/examples for the lights.  We'll provide you with a three.js scene with some virtual lights - you can animate them using whatever input you'd like, then we can hook them up to the real lights whenever you're ready.
2. Help us plug in, arrange & measure some sets of fairy lights.  This involves measuring tapes, graph paper, stickers & making config files - it's tonnes and tonnes of fun.
3. If you fancy getting your hands dirty on the hardware/code/backend hacking side, that'd be really ace too - we've got a load of esp8266 micro controllers (flashed with NodeMCU/lua), which are controlled over udp from a nodejs server, which is connected with websockets to a ThreeJS frontend.

# Timings/Plan

12.15pm - Arrive / Hellos
12.30pm - Overview & Tutorial about how to set up and control lights
12.45pm - Discussion any ideas
1pm  - Start doing stuff
3pm - Afternoon check in with tea and biscuits
6pm - Show and tell

# Questions

* Do I need a laptop – … (no, but might help)
* Will food and drink be provided – … (not formally)
* I have young people, can I bring them – … (yes)

# todo:

* mention summer of hacks, adventure collective, hackspace & people.
